
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: api-tasks
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app/backend # Monte backend dans /app
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoDB

volumes:
  mongo_data:
